
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/cleverlyBakes
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    show-sql: true
server:
    port: 8443